version: '3' 

services:

  face-bokeh:
    build: ./face-bokeh
    container_name: face-bokeh
    ports:
      - "8001:8000"
    

  face-emotion:
    build: ./face-emotion
    container_name: face-emotion
    ports:
      - "8002:8000"

  main:
    build: .
    ports:
      - "8000:8000"
    environment:
      - SERVICE_BOKE=http://face-bokeh:8000/
      - SERVICE_EMOTION=http://face-emotion:8000/
    depends_on:
      - face-bokeh
      - face-emotion